apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ym02g7tw3-java-springboot 
  janus-idp.io/tekton: ym02g7tw3-java-springboot
  backstage.io/kubernetes-id: ym02g7tw3-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ym02g7tw3-java-springboot
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml